In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import os
import numpy as np
import re

In [2]:
dir_list=os.listdir('..')[:11]
dir_list.remove("fase11")

In [3]:
current=".."
total=pd.DataFrame(columns=[["PGV1","PGV2","PGV3","ATB1","ATB2","fase","OP"]])
total['PGV1']=total['PGV1'].astype("float64")
total['PGV2']=total['PGV2'].astype("float64")
total['PGV3']=total['PGV3'].astype("float64")

total['ATB1']=total['ATB1'].astype("float64")
total['ATB2']=total['ATB2'].astype("float64")

total['fase'] = total['fase'].astype(int)

test=pd.DataFrame(columns=[["PGV1","PGV2","PGV3","ATB1","ATB2","fase","OP"]])
test['PGV1']=test['PGV1'].astype("float64")
test['PGV2']=test['PGV2'].astype("float64")
test['PGV3']=test['PGV3'].astype("float64")

test['ATB1']=test['ATB1'].astype("float64")
test['ATB2']=test['ATB2'].astype("float64")



test['fase'] = test['fase'].astype(int)
i=0
for path, subdirs, files in os.walk(current):
    #print(subdirs)
    for name in files:
        if 'ref' in path or name[0:1] == ".":
            continue
        names=("BEP" in name or "DPL" in name or "PL" in name or "HL" in name or "FL" in name)
        heads=("h12" in name)# or "h18" in name or "h24" in name or "h30" in name)
        if name.endswith(".csv") and heads and names and "Properties" not in path and "fase11" not in path:
            name_=os.path.join(path, name)
            print(name_)
            df_read = pd.read_csv(name_)
            df=pd.DataFrame(df_read["PGV1"][:200000])
            df["PGV2"]=pd.DataFrame(df_read["PGV2"][:200000])
            df["PGV3"]=pd.DataFrame(df_read["PGV3"][:200000])
            
            df["ATB1"]=pd.DataFrame(df_read["ATB1"][:200000])
            df["ATB2"]=pd.DataFrame(df_read["ATB2"][:200000])
            
            df1=pd.DataFrame(df_read["PGV1"][200000:200000+40000])
            df1["PGV2"]=pd.DataFrame(df_read["PGV2"][200000:200000+40000])
            df1["PGV3"]=pd.DataFrame(df_read["PGV3"][200000:200000+40000])
            
            df1["ATB1"]=pd.DataFrame(df_read["ATB1"][200000:200000+40000])
            df1["ATB2"]=pd.DataFrame(df_read["ATB2"][200000:200000+40000])
            
            if "BEP" in name:
                #print("BEP")
                df["OP"]=str("BEP")
                df1["OP"]=str("BEP")
            if "DPL" in name:
                df["OP"]=str("DPL")
                df1["OP"]=str("DPL")
                                    

            
            x1 = np.linspace(0, len(df), len(df), endpoint = False)
            for fase in dir_list:
                if fase+"/" in path:
                    num=re.findall(r'\d+', fase)
                    df["fase"]=int(num[0])
                    df['fase'] = df['fase'].astype(int)
                    df1["fase"]=int(num[0])
                    df1['fase'] = df1['fase'].astype(int)
                    
                    
                    if total.empty:
                        total=df
                    if test.empty:
                        test=df1
                        
                    else:
                    #print(df,"--")
                    #total.loc[len(total.index)]=
                        #pd.merge([total,df],on = ['PGV1', 'fase'])
                        total=pd.concat([total,df])
                        test=pd.concat([test,df1])
#                     #df.plot()
#                     plt.scatter(df,range(len(df)), color = colors[i])
                    #plt.scatter(x1,df["PGV1"], color = colors[i],label=fase)
                    
                            
            i+=1
#plt.legend()
#plt.show()

../fase1/CSV_files/BEP/h12_1_BEP_data.csv
../fase1/CSV_files/DPL/h12_1_DPL_data.csv
../fase1/CSV_files/FL/h12_1_FL_data.csv
../fase1/CSV_files/HL/h12_1_HL_data.csv
../fase1/CSV_files/PL/h12_1_PL_data.csv
../fase10/CSV_files/BEP/h12_10_BEP_data.csv
../fase10/CSV_files/DPL/h12_10_DPL_data.csv
../fase10/CSV_files/FL/h12_10_FL_data.csv
../fase10/CSV_files/HL/h12_10_HL_data.csv
../fase10/CSV_files/PL/h12_10_PL_data.csv
../fase2/CSV_files/BEP/h12_2_BEP_data.csv
../fase2/CSV_files/DPL/h12_2_DPL_data.csv
../fase2/CSV_files/FL/h12_2_FL_data.csv
../fase2/CSV_files/HL/h12_2_HL_data.csv
../fase2/CSV_files/PL/h12_2_PL_data.csv
../fase3/CSV_files/BEP/h12_3_BEP_data.csv
../fase3/CSV_files/DPL/h12_3_DPL_data.csv
../fase3/CSV_files/FL/h12_3_FL_data.csv
../fase3/CSV_files/HL/h12_3_HL_data.csv
../fase3/CSV_files/PL/h12_3_PL_data.csv
../fase4/CSV_files/BEP/h12_4_BEP_data.csv
../fase4/CSV_files/DPL/h12_4_DPL_data.csv
../fase4/CSV_files/FL/h12_4_FL_data.csv
../fase4/CSV_files/HL/h12_4_HL_data.csv
../fase4/C

In [4]:
total[["PGV1","PGV2","PGV3","ATB1","ATB2"]]
new=total[["PGV1","PGV2","PGV3","ATB1","ATB2"]]

test[["PGV1","PGV2","PGV3","ATB1","ATB2"]]
new_test=test[["PGV1","PGV2","PGV3","ATB1","ATB2"]]

In [5]:
new=pd.DataFrame.to_numpy(new)

In [6]:
total.mean(axis='rows')

/tmp/ipykernel_5375/1994096901.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  total.mean(axis='rows')


PGV1    0.004795
PGV2    0.004445
PGV3    0.004743
ATB1    0.058417
ATB2    0.226826
fase    5.500000
dtype: float64

In [7]:
x_train_std=np.array(total[["PGV1","PGV2","PGV3","ATB1","ATB2"]].std(axis='rows'))

In [8]:
total["PGV1"].std()

9.40983578666283e-05

In [9]:
test=test.reset_index(drop=True)

temp_data=np.array_split(new, 10)
temp_label=np.array_split(total["fase"], 10)


test_temp_data=np.array_split(new_test, 10)
test_temp_label=np.array_split(test["fase"], 10)

In [10]:
train_x=[]
train_y=[]
for i in range(len(temp_data)):
    #print(np.array_split(temp_data[i], 20))
    train_x.extend(np.array_split(temp_data[i], 10000*5))
    train_y.extend(np.array_split(temp_label[i],10000*5))
    
test_x=[]
test_y=[]
for i in range(len(test_temp_data)):
    #print(np.array_split(temp_data[i], 20))
    test_x.extend(np.array_split(test_temp_data[i], 2000*5))
    test_y.extend(np.array_split(test_temp_label[i], 2000*5))

In [11]:
len(train_x)

500000

In [12]:
train_x

[array([[0.00488134, 0.00446434, 0.00476717, 0.10171974, 0.1081215 ],
        [0.00487402, 0.00445921, 0.00476196, 0.08037794, 0.1288557 ],
        [0.00487227, 0.00445762, 0.00475779, 0.11574435, 0.0977544 ],
        [0.00487005, 0.00445098, 0.00475637, 0.08098771, 0.1556882 ],
        [0.00487898, 0.00445425, 0.00474793, 0.14379357, 0.11117065],
        [0.00486697, 0.00445255, 0.0047435 , 0.21940451, 0.03860093],
        [0.00487365, 0.00445119, 0.00474039, 0.18281857, 0.05750564],
        [0.00487788, 0.00446108, 0.00474546, 0.09074396, 0.09897405],
        [0.00487106, 0.00446334, 0.00474718, 0.07184123, 0.16117667],
        [0.00487031, 0.00446825, 0.00474585, 0.09562208, 0.16910445],
        [0.00486955, 0.00448135, 0.00475341, 0.10110998, 0.19410747],
        [0.00487373, 0.0044938 , 0.00476333, 0.12184201, 0.13861298],
        [0.00487849, 0.00450363, 0.00477504, 0.15659865, 0.12946553],
        [0.00488744, 0.00451451, 0.00477693, 0.17550138, 0.07641036],
        [0.00489267,

In [13]:
x_train_file = train_x
y_train_file = train_y
x_test_file = test_x
y_test_file = test_y
# Create empty lists
x_train = []
y_train = []
x_test = []
y_test = []

x_train = np.array(train_x)
y_train = np.array(train_y)
x_test = np.array(test_x)
y_test = np.array(test_y)

In [14]:
temp_=[]
temp=[]
for num in range(len(y_train)):
    temp_.append(np.average(y_train[num]))
for num in range(len(y_test)):
    temp.append(np.average(y_test[num]))

In [15]:
arr_ = np.array(temp_)
arr=np.array(temp)

y_train=arr_
y_test=arr

In [16]:
# train_x=[]
# train_y=[]
# for i in range(len(temp_data)):
#     #print(np.array_split(temp_data[i], 20))
#     train_x.extend(np.array_split(temp_data[i], 200))
#     train_y.extend(np.array_split(temp_label[i], 200))
    
# test_x=[]
# test_y=[]
# for i in range(len(test_temp_data)):
#     #print(np.array_split(temp_data[i], 20))
#     test_x.extend(np.array_split(test_temp_data[i], 50))
#     test_y.extend(np.array_split(test_temp_label[i], 50))

In [17]:
y_train=(y_train-1).astype(int)

In [18]:
y_test=(y_test-1).astype(int)

In [19]:
x_test.shape

(100000, 20, 5)

In [20]:
x_test[0].shape

(20, 5)

In [21]:
x_train_mean = x_train.mean(axis=0)
#x_train_std = x_train.std(axis=0)


In [22]:
x_train_mean=x_train_mean.mean(axis=0)

In [23]:
x_train_std

array([9.40983579e-05, 9.21413018e-05, 9.69814525e-05, 7.65434689e-02,
       6.36023502e-02])

In [24]:
#x_train_std=x_train_std.std(axis=0)

In [25]:
x_train_n = (x_train - x_train_mean)/(x_train_std)
x_test_n = (x_test - x_train_mean)/(x_train_std)
# x_train_n = x_train_n.reshape(x_train_n.shape + (1,1,))
# x_test_n = x_test_n.reshape(x_test_n.shape + (1,1,))

In [26]:
x_train_mean

array([0.00479533, 0.00444537, 0.00474285, 0.05841689, 0.22682632])

In [27]:
mean= pd.DataFrame(x_train_mean)
mean.to_csv("mean.csv")

In [28]:
x_train_std

array([9.40983579e-05, 9.21413018e-05, 9.69814525e-05, 7.65434689e-02,
       6.36023502e-02])

In [29]:
std= pd.DataFrame(x_train_std)
std.to_csv("std.csv")

In [30]:
x_train_std

array([9.40983579e-05, 9.21413018e-05, 9.69814525e-05, 7.65434689e-02,
       6.36023502e-02])

In [31]:
x_train_n

array([[[ 0.91401318,  0.20586637,  0.25078092,  0.56572883,
         -1.86635905],
        [ 0.83622928,  0.15020642,  0.19710725,  0.28690952,
         -1.54036158],
        [ 0.81763085,  0.13300067,  0.15403921,  0.74895295,
         -2.02935778],
        ...,
        [ 0.95799038,  0.99125054,  0.58404333,  2.22271214,
         -0.24595986],
        [ 1.00871626,  0.98342386,  0.61546056,  0.88437947,
         -1.26230491],
        [ 1.00877963,  0.99907721,  0.72388382,  0.05588781,
         -2.221121  ]],

       [[ 1.15192734,  1.03064264,  0.72200863,  0.69318908,
         -2.25947364],
        [ 1.09644889,  0.94338492,  0.75133547,  1.80050005,
         -2.31700261],
        [ 1.12201777,  0.83261484,  0.76264813,  0.95607586,
         -2.59505928],
        ...,
        [ 0.64961129,  0.26479282,  0.21438366,  0.31877459,
         -1.79924192],
        [ 0.66843151,  0.24642277,  0.2303382 ,  1.05167105,
         -2.59505928],
        [ 0.74586688,  0.32472186,  0.21665848, 

In [32]:
x_train

array([[[ 0.00488134,  0.00446434,  0.00476717,  0.10171974,
          0.1081215 ],
        [ 0.00487402,  0.00445921,  0.00476196,  0.08037794,
          0.1288557 ],
        [ 0.00487227,  0.00445762,  0.00475779,  0.11574435,
          0.0977544 ],
        ...,
        [ 0.00488548,  0.00453671,  0.00479949,  0.22855099,
          0.2111827 ],
        [ 0.00489025,  0.00453598,  0.00480254,  0.12611037,
          0.14654076],
        [ 0.00489026,  0.00453743,  0.00481305,  0.06269474,
          0.0855578 ]],

       [[ 0.00490373,  0.00454033,  0.00481287,  0.11147599,
          0.08311849],
        [ 0.00489851,  0.00453229,  0.00481571,  0.19623341,
          0.07945951],
        [ 0.00490091,  0.00452209,  0.00481681,  0.13159826,
          0.06177445],
        ...,
        [ 0.00485646,  0.00446977,  0.00476364,  0.08281701,
          0.11239031],
        [ 0.00485823,  0.00446808,  0.00476519,  0.13891544,
          0.06177445],
        [ 0.00486552,  0.00447529,  0.00476386, 

In [33]:
# import tensorflow as tf
# print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))

In [34]:
# print(tf.__version__)

In [35]:
# import tensorflow as tf
# from tensorflow.keras import layers, models

# # Assuming you have your time series data stored in 'X_train' and corresponding labels in 'y_train'
# # from sklearn.preprocessing import MinMaxScaler

# # # Assuming you have your time series data stored in 'X_train' and corresponding labels in 'y_train'

# # # Normalize the time series data
# # scaler = MinMaxScaler()
# # x_train_normalized = scaler.fit_transform(x_train)

# model = models.Sequential()
# model.add(layers.Conv1D(128, 8, activation='relu', input_shape=(20, 5)))
# model.add(layers.SpatialDropout1D(0.2))
# model.add(layers.BatchNormalization())
# model.add(layers.MaxPooling1D(2))

# model.add(layers.Conv1D(256, 5, activation='relu'))
# model.add(layers.SpatialDropout1D(0.3))
# model.add(layers.BatchNormalization())
# model.add(layers.MaxPooling1D(2))

# model.add(layers.Conv1D(128, 3, activation='relu'))
# model.add(layers.SpatialDropout1D(0.3))
# model.add(layers.BatchNormalization())
# model.add(layers.MaxPooling1D(2))

# model.add(layers.Flatten())
# #model.add(layers.GlobalAveragePooling1D())

# model.add(layers.Dense(128, activation='relu'))
# model.add(layers.Dense(10, activation='softmax')) # Replace 'num_classes' with the number of output classes

# # Compile the model
# model.compile(optimizer='adam',loss=tf.keras.losses.CategoricalCrossentropy(), metrics=['accuracy'])

# # Reshape your training data to match the input shape of the model
# #x_train = x_train.reshape((x_train.shape[0], 915, 1))
# # x_train_normalized = x_train_n.reshape((x_train_n.shape[0], 915, 2,1))
# # Train the model
# model.fit(x_train_n, tf.keras.utils.to_categorical(y_train), epochs=10, batch_size=16)

# # Assuming you have your test data stored in 'X_test' and corresponding labels in 'y_test'

# # Reshape your test data to match the input shape of the model
# #x_test = x_test.reshape((x_test.shape[0], 915, 1))
# #x_test_normalized = scaler.transform(x_test)

# # Reshape your normalized test data to match the input shape of the model
# # x_test_normalized = x_test_n.reshape((x_test_n.shape[0], 915, 2,1))
# # Evaluate the model
# test_loss, test_acc = model.evaluate(x_test_n, tf.keras.utils.to_categorical(y_test), verbose=2)
# print("Test accuracy:", test_acc)


In [ ]:
import tensorflow as tf
from tensorflow.keras import layers, models

# Assuming you have your time series data stored in 'X_train' and corresponding labels in 'y_train'
from sklearn.preprocessing import MinMaxScaler
optimizer = tf.keras.optimizers.Adam(
    learning_rate=0.001,
    beta_1=0.9,
    beta_2=0.999,
    epsilon=1e-8
)
# Assuming you have your time series data stored in 'X_train' and corresponding labels in 'y_train'

# Normalize the time series data
# scaler = MinMaxScaler()
# x_train_normalized = scaler.fit_transform(x_train)

model = models.Sequential()
model.add(layers.Conv1D(128, 8, activation='relu', input_shape=(20, 5)))
#model.add(layers.SpatialDropout1D(0.2))
model.add(layers.BatchNormalization())
#model.add(layers.MaxPooling1D(2))

model.add(layers.Conv1D(256, 5, activation='relu'))
#model.add(layers.SpatialDropout1D(0.3))
model.add(layers.BatchNormalization())
#model.add(layers.MaxPooling1D(2))

model.add(layers.Conv1D(128, 3, activation='relu'))
#model.add(layers.SpatialDropout1D(0.3))
model.add(layers.BatchNormalization())
#model.add(layers.MaxPooling1D(2))

#model.add(layers.Flatten())
model.add(layers.GlobalAveragePooling1D())


#model.add(layers.Dense(64, activation='relu',kernel_regularizer=tf.keras.regularizers.l2(0.1)))
model.add(layers.Dense(10, activation='softmax')) # Replace 'num_classes' with the number of output classes

# Compile the model
model.compile(optimizer=optimizer,loss=tf.keras.losses.CategoricalCrossentropy(), metrics=['accuracy'])

# Reshape your training data to match the input shape of the model
#x_train = x_train.reshape((x_train.shape[0], 915, 1))
#x_train_normalized = x_train_normalized.reshape((x_train_normalized.shape[0], 915, 1))
# Train the model
model.fit(x_train_n, tf.keras.utils.to_categorical(y_train), epochs=10, batch_size=16)

# Assuming you have your test data stored in 'X_test' and corresponding labels in 'y_test'

# Reshape your test data to match the input shape of the model
#x_test = x_test.reshape((x_test.shape[0], 915, 1))
#x_test_normalized = scaler.transform(x_test)

# Reshape your normalized test data to match the input shape of the model
#x_test_normalized = x_test_normalized.reshape((x_test_normalized.shape[0], 915, 1))
# Evaluate the model
test_loss, test_acc = model.evaluate(x_test_n, tf.keras.utils.to_categorical(y_test), verbose=2)
print("Test accuracy:", test_acc)


2023-07-30 13:42:51.790410: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-07-30 13:42:52.437236: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2023-07-30 13:42:53.570926: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:996] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-07-30 13:42:53.591256: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1956] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GP

Epoch 1/10


2023-07-30 13:42:53.817766: W tensorflow/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 200000000 exceeds 10% of free system memory.


31250/31250 [==============================] - 103s 3ms/step - loss: 0.7775 - accuracy: 0.7117
Epoch 2/10
31250/31250 [==============================] - 103s 3ms/step - loss: 0.5656 - accuracy: 0.7931
Epoch 3/10
31250/31250 [==============================] - 103s 3ms/step - loss: 0.5081 - accuracy: 0.8135
Epoch 4/10
31250/31250 [==============================] - 104s 3ms/step - loss: 0.4752 - accuracy: 0.8253
Epoch 5/10
31250/31250 [==============================] - 104s 3ms/step - loss: 0.4522 - accuracy: 0.8339
Epoch 6/10
31250/31250 [==============================] - 104s 3ms/step - loss: 0.4357 - accuracy: 0.8403
Epoch 7/10
31250/31250 [==============================] - 103s 3ms/step - loss: 0.4203 - accuracy: 0.8458
Epoch 8/10
31250/31250 [==============================] - 104s 3ms/step - loss: 0.4103 - accuracy: 0.8495
Epoch 9/10
31250/31250 [==============================] - 104s 3ms/step - loss: 0.4017 - accuracy: 0.8524
Epoch 10/10
17831/31250 [================>.............] 

In [ ]:
model.save("model_l20_e10_ns_np.h5")

In [ ]:
# import tensorflow as tf
# from tensorflow.keras import layers, models

# # Assuming you have your time series data stored in 'X_train' and corresponding labels in 'y_train'
# from sklearn.preprocessing import MinMaxScaler
# optimizer = tf.keras.optimizers.Adam(
#     learning_rate=0.001,
#     beta_1=0.9,
#     beta_2=0.999,
#     epsilon=1e-8
# )
# # Assuming you have your time series data stored in 'X_train' and corresponding labels in 'y_train'

# # Normalize the time series data
# # scaler = MinMaxScaler()
# # x_train_normalized = scaler.fit_transform(x_train)

# model = models.Sequential()
# model.add(layers.Conv1D(128, 8, activation='relu', input_shape=(20, 5)))
# model.add(layers.SpatialDropout1D(0.2))
# model.add(layers.BatchNormalization())
# #model.add(layers.MaxPooling1D(2))

# model.add(layers.Conv1D(256, 5, activation='relu'))
# model.add(layers.SpatialDropout1D(0.3))
# model.add(layers.BatchNormalization())
# #model.add(layers.MaxPooling1D(2))

# model.add(layers.Conv1D(128, 3, activation='relu'))
# model.add(layers.SpatialDropout1D(0.3))
# model.add(layers.BatchNormalization())
# #model.add(layers.MaxPooling1D(2))

# #model.add(layers.Flatten())
# model.add(layers.GlobalAveragePooling1D())


# #model.add(layers.Dense(64, activation='relu',kernel_regularizer=tf.keras.regularizers.l2(0.1)))
# model.add(layers.Dense(10, activation='softmax')) # Replace 'num_classes' with the number of output classes

# # Compile the model
# model.compile(optimizer=optimizer,loss=tf.keras.losses.CategoricalCrossentropy(), metrics=['accuracy'])

# # Reshape your training data to match the input shape of the model
# #x_train = x_train.reshape((x_train.shape[0], 915, 1))
# #x_train_normalized = x_train_normalized.reshape((x_train_normalized.shape[0], 915, 1))
# # Train the model
# model.fit(x_train_n, tf.keras.utils.to_categorical(y_train), epochs=15, batch_size=16)

# # Assuming you have your test data stored in 'X_test' and corresponding labels in 'y_test'

# # Reshape your test data to match the input shape of the model
# #x_test = x_test.reshape((x_test.shape[0], 915, 1))
# #x_test_normalized = scaler.transform(x_test)

# # Reshape your normalized test data to match the input shape of the model
# #x_test_normalized = x_test_normalized.reshape((x_test_normalized.shape[0], 915, 1))
# # Evaluate the model
# test_loss, test_acc = model.evaluate(x_test_n, tf.keras.utils.to_categorical(y_test), verbose=2)
# print("Test accuracy:", test_acc)


In [ ]:
# import tensorflow as tf
# from tensorflow.keras import layers, models

# # Assuming you have your time series data stored in 'X_train' and corresponding labels in 'y_train'
# from sklearn.preprocessing import MinMaxScaler
# optimizer = tf.keras.optimizers.Adam(
#     learning_rate=0.001,
#     beta_1=0.9,
#     beta_2=0.999,
#     epsilon=1e-8
# )
# # Assuming you have your time series data stored in 'X_train' and corresponding labels in 'y_train'

# # Normalize the time series data
# # scaler = MinMaxScaler()
# # x_train_normalized = scaler.fit_transform(x_train)

# model = models.Sequential()
# model.add(layers.Conv1D(128, 8, activation='relu', input_shape=(20, 5)))
# model.add(layers.SpatialDropout1D(0.2))
# model.add(layers.BatchNormalization())
# #model.add(layers.MaxPooling1D(2))

# model.add(layers.Conv1D(256, 5, activation='relu'))
# model.add(layers.SpatialDropout1D(0.3))
# model.add(layers.BatchNormalization())
# #model.add(layers.MaxPooling1D(2))

# model.add(layers.Conv1D(128, 3, activation='relu'))
# model.add(layers.SpatialDropout1D(0.3))
# model.add(layers.BatchNormalization())
# #model.add(layers.MaxPooling1D(2))

# #model.add(layers.Flatten())
# model.add(layers.GlobalAveragePooling1D())


# #model.add(layers.Dense(64, activation='relu',kernel_regularizer=tf.keras.regularizers.l2(0.1)))
# model.add(layers.Dense(10, activation='softmax')) # Replace 'num_classes' with the number of output classes

# # Compile the model
# model.compile(optimizer=optimizer,loss=tf.keras.losses.CategoricalCrossentropy(), metrics=['accuracy'])

# # Reshape your training data to match the input shape of the model
# #x_train = x_train.reshape((x_train.shape[0], 915, 1))
# #x_train_normalized = x_train_normalized.reshape((x_train_normalized.shape[0], 915, 1))
# # Train the model
# model.fit(x_train_n, tf.keras.utils.to_categorical(y_train), epochs=25, batch_size=16)

# # Assuming you have your test data stored in 'X_test' and corresponding labels in 'y_test'

# # Reshape your test data to match the input shape of the model
# #x_test = x_test.reshape((x_test.shape[0], 915, 1))
# #x_test_normalized = scaler.transform(x_test)

# # Reshape your normalized test data to match the input shape of the model
# #x_test_normalized = x_test_normalized.reshape((x_test_normalized.shape[0], 915, 1))
# # Evaluate the model
# test_loss, test_acc = model.evaluate(x_test_n, tf.keras.utils.to_categorical(y_test), verbose=2)
# print("Test accuracy:", test_acc)


In [ ]:
# import tensorflow as tf
# from tensorflow.keras import layers, models

# # Assuming you have your time series data stored in 'X_train' and corresponding labels in 'y_train'
# from sklearn.preprocessing import MinMaxScaler
# optimizer = tf.keras.optimizers.Adam(
#     learning_rate=0.001,
#     beta_1=0.9,
#     beta_2=0.999,
#     epsilon=1e-8
# )
# # Assuming you have your time series data stored in 'X_train' and corresponding labels in 'y_train'

# # Normalize the time series data
# # scaler = MinMaxScaler()
# # x_train_normalized = scaler.fit_transform(x_train)

# model = models.Sequential()
# model.add(layers.Conv1D(128, 8, activation='relu', input_shape=(915, 5)))
# model.add(layers.SpatialDropout1D(0.2))
# model.add(layers.BatchNormalization())
# #model.add(layers.MaxPooling1D(2))

# model.add(layers.Conv1D(256, 5, activation='relu'))
# model.add(layers.SpatialDropout1D(0.3))
# model.add(layers.BatchNormalization())
# #model.add(layers.MaxPooling1D(2))

# model.add(layers.Conv1D(128, 3, activation='relu'))
# model.add(layers.SpatialDropout1D(0.3))
# model.add(layers.BatchNormalization())
# #model.add(layers.MaxPooling1D(2))

# #model.add(layers.Flatten())
# model.add(layers.GlobalAveragePooling1D())


# #model.add(layers.Dense(64, activation='relu',kernel_regularizer=tf.keras.regularizers.l2(0.1)))
# model.add(layers.Dense(10, activation='softmax')) # Replace 'num_classes' with the number of output classes

# # Compile the model
# model.compile(optimizer=optimizer,loss=tf.keras.losses.CategoricalCrossentropy(), metrics=['accuracy'])

# # Reshape your training data to match the input shape of the model
# #x_train = x_train.reshape((x_train.shape[0], 915, 1))
# #x_train_normalized = x_train_normalized.reshape((x_train_normalized.shape[0], 915, 1))
# # Train the model
# model.fit(x_train_n, tf.keras.utils.to_categorical(y_train), epochs=10, batch_size=16)

# # Assuming you have your test data stored in 'X_test' and corresponding labels in 'y_test'

# # Reshape your test data to match the input shape of the model
# #x_test = x_test.reshape((x_test.shape[0], 915, 1))
# #x_test_normalized = scaler.transform(x_test)

# # Reshape your normalized test data to match the input shape of the model
# #x_test_normalized = x_test_normalized.reshape((x_test_normalized.shape[0], 915, 1))
# # Evaluate the model
# test_loss, test_acc = model.evaluate(x_test_n, tf.keras.utils.to_categorical(y_test), verbose=2)
# print("Test accuracy:", test_acc)


In [ ]:
y_test.shape

In [ ]:
# import tensorflow as tf
# from tensorflow.keras import layers, models

# # Assuming you have your time series data stored in 'X_train' and corresponding labels in 'y_train'
# from sklearn.preprocessing import MinMaxScaler
# optimizer = tf.keras.optimizers.Adam(
#     learning_rate=0.001,
#     beta_1=0.9,
#     beta_2=0.999,
#     epsilon=1e-8
# )
# # Assuming you have your time series data stored in 'X_train' and corresponding labels in 'y_train'

# # Normalize the time series data
# # scaler = MinMaxScaler()
# # x_train_normalized = scaler.fit_transform(x_train)

# model = models.Sequential()
# model.add(layers.Conv1D(128, 8, activation='relu', input_shape=(915, 5)))
# model.add(layers.SpatialDropout1D(0.2))
# model.add(layers.BatchNormalization())
# #model.add(layers.MaxPooling1D(2))

# model.add(layers.Conv1D(256, 5, activation='relu'))
# model.add(layers.SpatialDropout1D(0.3))
# model.add(layers.BatchNormalization())
# #model.add(layers.MaxPooling1D(2))

# model.add(layers.Conv1D(128, 3, activation='relu'))
# model.add(layers.SpatialDropout1D(0.3))
# model.add(layers.BatchNormalization())
# #model.add(layers.MaxPooling1D(2))

# #model.add(layers.Flatten())
# model.add(layers.GlobalAveragePooling1D())


# #model.add(layers.Dense(64, activation='relu',kernel_regularizer=tf.keras.regularizers.l2(0.1)))
# model.add(layers.Dense(10, activation='softmax')) # Replace 'num_classes' with the number of output classes

# # Compile the model
# model.compile(optimizer=optimizer,loss=tf.keras.losses.CategoricalCrossentropy(), metrics=['accuracy'])

# # Reshape your training data to match the input shape of the model
# #x_train = x_train.reshape((x_train.shape[0], 915, 1))
# #x_train_normalized = x_train_normalized.reshape((x_train_normalized.shape[0], 915, 1))
# # Train the model
# model.fit(x_train_n, tf.keras.utils.to_categorical(y_train), epochs=10, batch_size=16)

# # Assuming you have your test data stored in 'X_test' and corresponding labels in 'y_test'

# # Reshape your test data to match the input shape of the model
# #x_test = x_test.reshape((x_test.shape[0], 915, 1))
# #x_test_normalized = scaler.transform(x_test)

# # Reshape your normalized test data to match the input shape of the model
# #x_test_normalized = x_test_normalized.reshape((x_test_normalized.shape[0], 915, 1))
# # Evaluate the model
# test_loss, test_acc = model.evaluate(x_test_n, tf.keras.utils.to_categorical(y_test), verbose=2)
# print("Test accuracy:", test_acc)


In [ ]:
test_acc

In [ ]:
#model.predict()

In [ ]:
tf.keras.utils.to_categorical(y_test)

In [ ]:
x_test[5].shape

In [ ]:
t=model.predict(tf.expand_dims(x_test_n[80], axis=0))
t

In [ ]:
np.argmax(t, axis=1)

In [ ]:
t=model.predict(tf.expand_dims(x_test_n[190], axis=0))
t

In [ ]:
np.argmax(t, axis=1)

In [ ]:
t=model.predict(tf.expand_dims(x_test_n[10017], axis=0))
t

In [ ]:
x_test_n[10017],y_test[10017]

In [ ]:
np.argmax(t, axis=1)

In [ ]:
y_test[19]

In [ ]:
y_pred[191]

In [ ]:
from sklearn.metrics import confusion_matrix
y_pred = model.predict(x_test_n)
y_pred = np.argmax(y_pred, axis=1)
#y = np.argmax(Y, axis=-1)
conf_mat = confusion_matrix(y_test, y_pred)


In [ ]:
y_pred

In [ ]:
import seaborn as sns

In [ ]:
#cm_df = pd.DataFrame(conf_mat, index = ['0','9','1','2','3','4','5','6','7','8'], 
#                     columns = ['0','9','1','2','3','4','5','6','7','8'])

#Plotting the confusion matrix
plt.figure(figsize=(25,20))
sns.heatmap(conf_mat, annot=True)
plt.title('Confusion Matrix')
plt.ylabel('Actal Values')
plt.xlabel('Predicted Values')
plt.show()